openapi: 3.0.0
info:
  title: 薪资模块 API
  description: 提供薪资记录的创建、查询、更新、删除、计算和支付处理等功能。
  version: 1.0.0
tags:
  - name: 薪资管理
    description: 员工薪资记录的管理和处理

paths:
  /api/payroll:
    get:
      tags:
        - 薪资管理
      summary: 分页获取薪资记录
      description: 返回所有薪资记录，支持分页和排序。
      operationId: getAllPayrollLedgers
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 10
        - name: sort
          in: query
          schema:
            type: string
            default: "id,asc"
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedPayrollLedger'
        '401':
          description: 未经授权
        '403':
          description: 禁止访问

    post:
      tags:
        - 薪资管理
      summary: 创建薪资记录
      description: 创建一条新的薪资记录。
      operationId: createPayrollLedger
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayrollLedgerDTO'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayrollLedgerDTO'
        '400':
          description: 无效的请求
        '401':
          description: 未经授权
        '403':
          description: 禁止访问

  /api/payroll/{id}:
    get:
      tags:
        - 薪资管理
      summary: 获取单条薪资记录
      description: 根据ID获取指定的薪资记录。
      operationId: getPayrollLedger
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayrollLedgerDTO'
        '401':
          description: 未经授权
        '403':
          description: 禁止访问
        '404':
          description: 未找到

    put:
      tags:
        - 薪资管理
      summary: 更新薪资记录
      description: 更新指定ID的薪资记录。
      operationId: updatePayrollLedger
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayrollLedgerDTO'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayrollLedgerDTO'
        '400':
          description: 无效的请求
        '401':
          description: 未经授权
        '403':
          description: 禁止访问
        '404':
          description: 未找到

    delete:
      tags:
        - 薪资管理
      summary: 删除薪资记录
      description: 删除指定ID的薪资记录。
      operationId: deletePayrollLedger
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 删除成功
        '401':
          description: 未经授权
        '403':
          description: 禁止访问
        '404':
          description: 未找到

  /api/payroll/search:
    post:
      tags:
        - 薪资管理
      summary: 搜索薪资记录
      description: 根据复合条件分页搜索薪资记录。
      operationId: searchPayrollLedgers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayrollSearchCriteria'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedPayrollLedger'
        '401':
          description: 未经授权
        '403':
          description: 禁止访问

  /api/payroll/calculate:
    post:
      tags:
        - 薪资管理
      summary: 计算薪资
      description: 根据传入的数据计算薪资的各个组成部分。
      operationId: calculatePayroll
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayrollLedgerDTO'
      responses:
        '200':
          description: 计算成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayrollLedgerDTO'
        '401':
          description: 未经授权
        '403':
          description: 禁止访问

  /api/payroll/{id}/status:
    put:
      tags:
        - 薪资管理
      summary: 更新薪资记录状态
      description: 更新指定薪资记录的状态（如：待处理、已支付）。
      operationId: updatePayrollStatus
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: status
          in: query
          required: true
          schema:
            type: string
            enum: [PENDING, PROCESSING, PAID, FAILED]
      responses:
        '200':
          description: 状态更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayrollLedgerDTO'
        '401':
          description: 未经授权
        '403':
          description: 禁止访问
        '404':
          description: 未找到

  /api/payroll/generate/{year}/{month}:
    post:
      tags:
        - 薪资管理
      summary: 为所有员工生成薪资记录
      description: 为指定月份的所有在职员工批量生成薪资记录。
      operationId: generatePayrollLedgers
      security:
        - bearerAuth: []
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: integer
        - name: month
          in: path
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: 生成成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PayrollLedgerDTO'
        '401':
          description: 未经授权
        '403':
          description: 禁止访问

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PayrollLedgerDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        employeeId:
          type: integer
          format: int64
        employeeName:
          type: string
          readOnly: true
        departmentId:
          type: integer
          format: int64
          readOnly: true
        departmentName:
          type: string
          readOnly: true
        payPeriod:
          type: string
          format: "YYYY-MM"
          example: "2024-07"
        baseSalary:
          type: number
          format: double
        overtimePay:
          type: number
          format: double
        bonus:
          type: number
          format: double
        allowances:
          type: number
          format: double
        taxDeductions:
          type: number
          format: double
        insuranceDeductions:
          type: number
          format: double
        otherDeductions:
          type: number
          format: double
        netSalary:
          type: number
          format: double
        grossSalary:
          type: number
          format: double
          readOnly: true
        totalDeductions:
          type: number
          format: double
          readOnly: true
        paymentDate:
          type: string
          format: date
        paymentReference:
          type: string
        notes:
          type: string
        status:
          type: string
          enum: [PENDING, PROCESSING, PAID, FAILED]

    PayrollSearchCriteria:
      type: object
      properties:
        employeeId:
          type: integer
          format: int64
        departmentId:
          type: integer
          format: int64
        startPayPeriod:
          type: string
          format: "YYYY-MM"
        endPayPeriod:
          type: string
          format: "YYYY-MM"
        status:
          type: string
          enum: [PENDING, PROCESSING, PAID, FAILED]
        minNetSalary:
          type: number
          format: double
        maxNetSalary:
          type: number
          format: double

    PagedPayrollLedger:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/PayrollLedgerDTO'
        pageable:
          type: object
        totalPages:
          type: integer
        totalElements:
          type: integer
        last:
          type: boolean
        size:
          type: integer
        number:
          type: integer
        sort:
          type: object
        numberOfElements:
          type: integer
        first:
          type: boolean
        empty:
          type: boolean